name: test-coverage

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        r-version: [3.5, 3.6, 4.0]

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
